#!/bin/bash
# if "$SNAP/quake-engine" exists we can expect this to run
# as a content snap within, say, a Quake map editor.
# On the confinement side the script runs within the parents sandbox.

QUAKE_ENGINE=quakespasm

if [ -d "$SNAP/quake-engine" ]; then
    export SNAP="${SNAP}/quake-engine"
fi

# if GAMEFILES_PATH is still empty use zenity dialog
if [ "$@" == "" ]; then
    GAMEFILES_PATH=`zenity \
      --file-selection \
      --directory \
      --title='Select the id1 directory containing Quake game files (pak0.pak, pak1.pak ...)'`
    
    # We actually need the parent directory
    GAMEFILES_PATH=$(dirname "${GAMEFILES_PATH}")
    exec "desktop-launch" "$QUAKE_ENGINE" "-basedir" "$GAMEFILES_PATH"
else
    exec "desktop-launch" "$QUAKE_ENGINE" "$@"
fi
