#!/bin/bash
# if "$SNAP/quake-engine" exists we can expect this to run
# as a content snap within, say, a Quake map editor.
# On the confinement side the script runs within the parents sandbox.

QUAKE_ENGINE=quakespasm

if [ -d "$SNAP/quake-engine" ]; then
    export SNAP="${SNAP}/quake-engine"
fi

export PATH="$SNAP/usr/sbin:$SNAP/usr/bin:$SNAP/sbin:$SNAP/bin:$PATH"
export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:$SNAP/lib:$SNAP/usr/lib:$SNAP/lib/x86_64-linux-gnu:$SNAP/usr/lib/x86_64-linux-gnu:$SNAP/usr/lib/x86_64-linux-gnu/mesa-egl"
export LD_LIBRARY_PATH="$SNAP/usr/lib/x86_64-linux-gnu:$LD_LIBRARY_PATH"
export LD_LIBRARY_PATH=$SNAP_LIBRARY_PATH:$LD_LIBRARY_PATH

# if GAMEFILES_PATH is still empty use zenity dialog
if [ "$@" == "" ]; then
    GAMEFILES_PATH=`zenity \
      --file-selection \
      --directory \
      --title='Select the id1 directory containing Quake game files (pak0.pak, pak1.pak ...)'`
    
    # We actually need the parent directory
    GAMEFILES_PATH=$(dirname "${GAMEFILES_PATH}")
    exec "$QUAKE_ENGINE" "-basedir" "$GAMEFILES_PATH"
else
    exec "$QUAKE_ENGINE" "$@"
fi
